version: '3.7'

services:
  backend:
    build: ./backend
    container_name: cm_backend_dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/backend/
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env.dev
    depends_on:
      - db
  db:
    build: ./db
    container_name: cm_db_dev
    volumes:
      - ./db/data:/db
    env_file:
      - ./db/.env.dev


